feat(client): add publish methods, migrate to @qiwi/npm-registry-client
qiwi/npm-batch-action pull request #14
Opened 2021-01-11 13:07 UTC by oljekechoro

2021-01-11 18:01 UTC, antongolub requested changes

2021-01-11 18:01 UTC, antongolub commented on packages/infra/tsconfig.compiler.json
> +    "typeRoots": ["../../node_modules/@types"]
Can be removed completely

2021-01-11 18:02 UTC, antongolub requested changes

2021-01-11 18:02 UTC, antongolub commented on packages/client/src/test/ts/wrapper.ts
> +beforeEach(() => jest.restoreAllMocks())
Just: 
```js
beforeEach( jest.restoreAllMocks)
```

2021-01-12 08:59 UTC, antongolub approved these changes

2021-01-12 09:03 UTC, pismenskiy approved these changes

2021-01-12 09:09 UTC, merged